# 0: 8 11
# (8, "42 | 42 8").                 WAS: 8: 42
# (11, "42 31 | 42 11 31").    WAS: 11: 42 31

# Have to run rule 42 AT LEAST twice before hitting "31"

ID: 42 => aaaaa,aaaa,aaa,aa,a,bbaab,bbaa,baa,aa,a,a,aaaaa,aaaa,aaa,aa,a,
ID: 31 => aabba,abba,bba,bb,abaaa,baaa,aaa,aa,a,aabab,abab,bab,ba

[aaaaa]     [bbaa]   [baaa]     [aababaa
   8:42        11:42   11:31


PART1 STR: bbabbbbaabaabba
PART2 STR: aaaaabbaabaaaaababaa
ID: 42, ((b(a(bb|ab)|b((a|b)(a|b)))|a(b(bb)|a(bb|a(a|b))))b|(((aa|ab)a|(bb)b)b|(((a|b)a|bb)a)a)a)
ID  8:  (((b(a(bb|ab)|b((a|b)(a|b)))|a(b(bb)|a(bb|a(a|b))))b|(((aa|ab)a|(bb)b)b|(((a|b)a|bb)a)a)a))

ID 11: (((b(a(bb|ab)|b((a|b)(a|b)))|a(b(bb)|a(bb|a(a|b))))b|(((aa|ab)a|(bb)b)b|(((a|b)a|bb)a)a)a)(b(b(a(ba)|b(aa))|a(b(ab|(a|b)a)|a(ba|ab)))|a(b((ab|(a|b)a)b|((a|b)a|bb)a)|a((ba)b|(ba|bb)a))))
ID: 31, (b(b(a(ba)|b(aa))|a(b(ab|(a|b)a)|a(ba|ab)))|a(b((ab|(a|b)a)b|((a|b)a|bb)a)|a((ba)b|(ba|bb)a)))





* Unit tests https://docs.python.org/3/library/unittest.html
** All tests
python3 -m unittest test
** One suite
python3 -m unittest test.TestRows
** One test
python3 -m unittest test.TestRows.test_example1Row


* PART 1
** MATCH RULES
*** numbered and build upon each other. For example:
    0: 1 2
    1: "a"
    2: 1 3 | 3 1
    3: "b"

*** Some rules, like 3: "b", simply match a single character (in this case, b).

***  The remaining rules list the sub-rules that must be followed;
**** e.g. the rule 0: 1 2 means that to match rule 0, the text being  checked must match rule 1, and 
**** the text after the part that matched rule 1 must then match rule 2.

     Some of the rules have multiple lists of sub-rules separated by a pipe
     (|). This means that at least one list of sub-rules must match. (The
     ones that match might be different each time the rule is encountered.)

     For example, the rule 2: 1 3 | 3 1 means that to match rule 2, the
     text being checked must match rule 1 followed by rule 3 or it must
     match rule 3 followed by rule 1.

     Fortunately, there are no loops in the rules, so the list of possible
     matches will be finite.

     Since rule 1 matches a and rule 3 matches b, rule 2 matches either ab
     or ba. Therefore, rule 0 matches aab or aba.

*** Here's a more interesting example:
    0: 4 1 5
    1: 2 3 | 3 2
    2: 4 4 | 5 5
    3: 4 5 | 5 4
    4: "a"
    5: "b"

****  Because rule 4 matches a and rule 5 matches b...
***** Rule 2 matches two letters that are the same (aa or bb),
***** Rule 3 matches two letters that are different (ab or ba).

***** Since rule 1 matches rules 2 and 3... once each in either order, it must...
****** Match two pairs of letters
******* one pair with matching letters
******* one pair with different letters

****** This leaves eight possibilities...
******* aaab
******* aaba
******* bbab
******* bbba
******* abaa
******* abbb
******* baaa
******* babb

***** Rule 0, therefore....
****** matches a (rule 4)
****** then any of the eight options from rule 1
****** then b (rule 5)
******* aaaabb
******* aaabab
******* abbabb
******* abbbab
******* aabaab
******* aabbbb
******* abaaab
******* ababbb

** MATCH INPUT STRINGS
*** Need to be checked against the rules 

** GOAL: determine the NUMBER of messages that completely match RULE 0. 
*** The WHOLE MESSAGE must match all of rule 0 
**** there can't be extra unmatched characters in the message
***** For example, aaaabbb might appear to match rule 0 above...
****** but it has an extra unmatched b on the end


*** In the above example...  the answer is "2"...
**** MATCH: ababbb and abbbab
**** NO MATCH: bababa, aaabbb, and aaaabbb 



** Unit Test Input
 0: 4 1 5
 1: 2 3 | 3 2
 2: 4 4 | 5 5
 3: 4 5 | 5 4
 4: "a"
 5: "b"

 ababbb
 bababa
 abbbab
 aaabbb


* PART 2
** Original rules
***  31: 14 17 | 1 13
  (b(b(a(ba)|b(aa))|a(b(ab|(a|b)a)|a(ba|ab)))|a(b((ab|(a|b)a)b|((a|b)a|bb)a)|a((ba)b|(ba|bb)a)))

*** 8: 42
  (((b(a(bb|ab)|b((a|b)(a|b)))|a(b(bb)|a(bb|a(a|b))))b|(((aa|ab)a|(bb)b)b|(((a|b)a|bb)a)a)a)) ==> 42

*** 11: 42 31
  (((b(a(bb|ab)|b((a|b)(a|b)))|a(b(bb)|a(bb|a(a|b))))b|(((aa|ab)a|(bb)b)b|(((a|b)a|bb)a)a)a)           ==> 42
   (b(b(a(ba)|b(aa))|a(b(ab|(a|b)a)|a(ba|ab)))|a(b((ab|(a|b)a)b|((a|b)a|bb)a)|a((ba)b|(ba|bb)a))))  ==> 31

  


* RULE 31 matches
   1 aaa
   1 aaab
   1 aab
   1 aaba
   1 abaaa
   1 baaa
   1 baaab
   1 baaba
   1 babba
   2 aabaa
   2 abbaa
   2 abbab
   2 bbab
   3 babab
   4 ab
   5 b
   5 babaa
   6 a
   6 aabab
   6 abbba
   6 baba
   6 bbaba
   6 bbba
   7 aba
   7 abaa
   9 aabba
   9 abab
  10 abba
  11 bab
  11 bbbaa
  13 bbaa
  15 bb
  16 bba
  17 aa
  20 ba
  20 baa

* RULE 42 matches
   1 bbbba
   2 aabb
   2 aabbb
   2 bbbbb
   3 aaaba
   3 baab
   3 baabb
   3 bbbb
   4 aaaaa
   5 baaa
   5 baaaa
   5 babb
   5 babbb
   5 bbba
   5 bbbab
   6 aaaab
   6 aaabb
   6 aba
   6 abab
   6 ababa
   6 bbaaa
   7 abb
   7 bbaab
   9 aaab
   9 aab
   9 abbb
   9 abbbb
  10 aaaa
  10 ba
  11 bba
  12 baa
  12 bbb
  13 aaa
  13 bbaa
  15 ab
  20 aa
  20 b
  25 bb
  29 a
